name: build-multiplatform-dockerimage
on:
 # Trigger the workflow on pull requests,
  # but only for the main branch
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  build_image:
    name: build a multi platform Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build Images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: false
          target: test_image
            